apiLink: 'https://api.github.com/repos/TreeboMC/TreeboTeleport/releases/latest'
releasePage: 'https://github.com/TreeboMC/TreeboTeleport/releases/latest'
checkUpdates: 'true'

host: ''
database: ''
username: ''
password: ''
transferTable: ' '