apiLink: 'https://api.github.com/repos/TreeboMC/TreeboTeleport/releases/latest'
releasePage: 'https://github.com/TreeboMC/TreeboTeleport/releases/latest'
checkUpdates: 'true'

host: ''
database: ''
username: ''
password: ''
transferTable: 'treeboTeleport_serverTransfer'

teleportProtection: 3
CommandDelay: 15
useCooldown: false

isHubServer: false

KillZombies: false
ReplacePhantomsWithPissedOffWolves: true

general:
  serverName: 'Test'
  disableTPSafety: false
  messages:
    badge: '&6[Treebo Teleport]&r'
    error: '&4ERROR:&r'

disabledCommands:
  AddMaxHomes: false
  Back: false
  Bed: false
  ClearMyChat: false
  hub: false
  wild: false
  gws: false
  sws: false
  tp: false
  tpaherenew: false
  tpa: false
  tpask: false
  tpok: false
  tpaccept: false
  tpyes: false
  givehubitem: false
  setwarp: false
  deletewarp: false
  delwarp: false
  warp: false
  warps: false
  sethome: false
  delhome: false
  home: false
  homes: false
  bed: false
  setworldspawn: false
  spawn: false
  sendspawn: false
  ttelereload: false
  configurehub: false
  configurewarps: false
  configurehomes: false
  clearmychat: false
  ttelesaveconfig: false
  tteleversion: false
  nameit: false
  tptoggle: false
  disabletpsafety: false
  tpno: false
  tpdeny: false
  tpcancel: false
  back: false
  addmaxhomes: false
  showmaxhomes: false
  shop: false
  setshop: false
  setttelecooldown: false
  fixskygridhomes: true
  restoreplayerinventory: false
  toggledeathdocket: false

wild:
  messages:
    success: '&3&l[&3Treebo Teleport&3&l] &2Sending you to: &f{COORDS}'
    failure: '&3&l[&3Treebo Teleport&3&l] &4Unable to locate safe spot. Please try again shortly'
  minX: -500000
  maxX: 500000
  minY: 30
  maxY: 150
  minZ: -500000
  maxZ: 500000

deathDocket:
  disable: false
  toggle: